### PR TITLE
927 Github workflow failing 

### LINKED ISSUE #927: Github workflow failing
**Describe the bug**
Github workflow failing due to mypy and protobuf version conflicts.

**To Reproduce**
Run workflow

**Expected behavior**
Successfully complete all the actions

**Screenshots**
image

### PR DESCRIPTION
**Pull request by nikhilranjan7**
This PR fixes #927 . 

### Description of changes
Describe what are the changes, and how they solve the problem.
Change versions and remove type ignore

### Possible influences of this PR.
Describe what are the possible side-effects of the code change.
Type checking error might arise

### Test Conducted
Describe what test cases are included for the PR.
All the testcases as running previously

### CODE REVIEW

**Review by hunterhector — DISMISSED** [review]
Thanks, if the workflow run successfully this should be OK.

**Comment by nikhilranjan7** [comment]
@hunterhector this workflow was cancelled somehow. Can you help rerun again, I have access to Fortehealth only, not this one.

**Comment by hunterhector** [comment]
> @hunterhector this workflow was cancelled somehow. Can you help rerun again, I have access to Fortehealth only, not this one.

I have already re-run it once. Got cancelled again, need to look at what happens.

**Comment by nikhilranjan7** [comment]
I am not sure what is the error here, even the failed log is not visible, but everything passes correctly in my fork. https://github.com/nikhilranjan7/forte/actions/runs/4553632167

**Comment by hunterhector** [comment]
> I am not sure what is the error here, even the failed log is not visible, but everything passes correctly in my fork. https://github.com/nikhilranjan7/forte/actions/runs/4553632167 Might be timeout, can we try rerunning only the failed jobs ?

Could be a time out on the limits. I don't know the answer now, let's look for causes/solutions for this.

I did try rerunning only the failed jobs but it doesn't seem to work. But I can at least add you to the Forte developer list so you don't need approvals

**Comment by hunterhector** [comment]
> I am not sure what is the error here, even the failed log is not visible, but everything passes correctly in my fork. https://github.com/nikhilranjan7/forte/actions/runs/4553632167 Might be timeout, can we try rerunning only the failed jobs ?

I have added you to the developers (you should have an invite in the email). Then you should be able to work with the workflow easily. 

Initially "re-run failed" doesn't work (for unknown reasons), but it seems to be running if I "enabled debug logging". Let's see if rerunning the failed jobs will work. I also suspect this is some github action limit, but we don't get clear error messages.

**Comment by hunterhector** [comment]
oh it works. Probably the old cache screws things up.

**Review by hunterhector — APPROVED** [review]

**Pull request merged**
