### PR TITLE
Inferring ontology tree automatically #583

### LINKED ISSUE #583: Inferring ontology tree automatically
**Is your feature request related to a problem? Please describe.**
The ontology tree is used in several places by Forte, it is mainly used to find all the entries (including subtype) of a top-level type, which is used in:
1. get entries of a particular type 
2. check output consistency between the components.

There could be other use of this piece of information. 

Currently, the ontology tree is loaded by [passing in the JSON file](https://github.com/asyml/forte/blob/master/forte/pipeline.py#L125), which is optional.  There are a couple of issues with this approach. The JSON files may not be ready or synchronized in all environments, and the parameter being optional also makes it sometimes neglected. Also, there could be more than one JSON file making it a bit hard to find them all.

Since the entry classes are available in the python environment, it might be possible to infer them by finding all sub-classes of `Entry`.

**Describe the solution you'd like**
We can recursively find subclasses from `Entry` via `__subclasses__`, and populate the `onto_specs_dict` and `merged_entry_tree` around [here](https://github.com/asyml/forte/blob/master/forte/pipeline.py#L318). 

Currently, we haven't evaluated the problems of this approach.

**Describe alternatives you've considered**

**Additional context**
The solution here can be used to partially address issue #570.

### PR DESCRIPTION
**Pull request by Xuezhi-Liang**
This PR fixes #583 

### Description of changes
Recursive Method to Find Subclasses to generate the ontology tree,

### Possible influences of this PR.
Describe what are the possible side-effects of the code change.

### Test Conducted
Evaluated the Recursive Method in tests/forte/advanced_pipeline_test.py.

### CODE REVIEW

**Comment by hunterhector** [comment]
Notice https://github.com/asyml/forte/issues/570 is an immediate follow up to this

**Review by qinzzz — COMMENTED** [review]
I tried to run your `parse_entry` function on `Entry` class, and there are a few problems:
1) The returned "definitions" is not a complete list of all classes. For example, classes in ft.onto.wikipedia and ft.onto.metric are not found.  `ConferenceGroup` that inherit `Group` and multiple class that inherit `Link` in base_ontology is also not found.
Part of this problem is caused by skipping entrys that start with `TOP_MOST_MODULE_NAME`
2) The returned list of "additional_prefixes" contains duplicate `ftx.onto`.
3) The test case is too simple and cannot reflect actual use case. Please add test cases with real classes in forte, e.g. Entry. All classes in ontology_specs/ should be included in the returning dictionary.

**Comment by hunterhector** [comment]
@feipenghe , @Xuezhi-Liang encountered a problem in building the doc, do you know what happen here?

**Comment by feipenghe** [comment]
> @feipenghe , @Xuezhi-Liang encountered a problem in building the doc, do you know what happen here?

@Xuezhi-Liang  I think it's because hyperlink for "Handling Structured Text Data" expired. Since it's not very important and I might change the hyperlink later to a notebook, you can remove the hyperlink.

**Comment by Xuezhi-Liang** [comment]
This issue is dependent on #issue570. I will recode this once #570 is solved.

**Comment by hunterhector** [comment]
closed by https://github.com/asyml/forte/issues/583#issuecomment-1047413208

**Pull request closed without merging**
